/* global goog, lime, obacht */
/* jshint devel:true */

goog.provide('obacht.Bonus');

// Obacht Requirements
goog.require('obacht.options');

// LimeJS Requirements
goog.require('lime.RoundedRect');
goog.require('lime.animation.Resize')

// Closure Library Requirements
goog.require('goog.pubsub.PubSub');

/**
 * Boni Object. Bonis are generated by the Server
 *
 * @constructor
 */
obacht.Bonus = function(type) {
	"use strict";
	/*var self = this;
	
	////////////////
    // ATTRIBUTES //
    ////////////////
	this.type = type;
	this.fill = obacht.options.bonus.general.path + this.type + '.png';


	////////////////////
    // LIMEJS OBJECTS //
    ////////////////////
	this.bonusButton = new lime.RoundedRect().setSize(obacht.options.bonus.general.size, obacht.options.bonus.general.size).setPosition(obacht.options.bonus.general.x, obacht.options.bonus.general.y).setFill(this.fill).setAnchorPoint(0, 0).setRadius(15);
    this.layer = new lime.Layer().setSize(obacht.options.graphics.VIEWPORT_WIDTH, obacht.options.graphics.VIEWPORT_HEIGHT);
    this.drawBonus();

    
    /////////////////////////
    // SUBSCRIBE TO EVENTS //
    /////////////////////////    
    goog.events.listen(this.bonusButton, ['touchstart', 'mousedown'], function(e) {
        this.checkTime();
    }); */
     
};

obacht.Bonus.prototype = {
   
    /**
     * Draw the bonus-button
     */
    drawBonus: function() {
        "use strict";
        this.layer.appendChild(this.bonusButton);
    },
    
    /**
     * Delete the bonus-button
     */
    deleteBonus: function() {
        "use strict";
        this.layer.removeChild(this.bonusButton);
    },
    
    checkTime: function() {
    "use strict";
    } 

};
