/* global goog, lime, obacht */
/* jshint devel:true */

goog.provide('obacht.Bonus');


/*
 * Boni Object. Bonis are generated by the Server
 *
 * @constructor
 */
obacht.Bonus = function(type) {

};

obacht.Bonus.prototype = {

};
