#!/bin/bash
# Evtl: sudo chmod +x start.sh

echo ''
echo '###########################'
echo '# Forever: Starte Server ##'
echo '###########################'
forever stop server.js
forever -o ~/.forever/obacht-out.log -e ~/.forever/obacht-err.log --append start obacht-server.js
echo 'Laufende Forever Prozesse:'
forever list
