#!/bin/bash
# Evtl: sudo chmod +x start

echo ''
echo ''
echo '###############################'
echo '# Forever: Starte GameServer  #'
echo '###############################'
echo ''
forever stop obacht-server.js
forever -o ~/.forever/obacht-out.log -e ~/.forever/obacht-err.log --append start obacht-server.js
echo '###############################'
echo '# Forever: Laufende Prozesse: #'
echo '###############################'
forever list
